"use client"

import { Button } from "@/components/ui/button"
import { ClipboardCopy, Check } from "lucide-react"
import { useState } from "react"
import { toast } from "sonner"

interface SummaryInjection {
  muscleId: string | null
  side: string
  units: number
}

interface SummaryTreatment {
  encounterLocalDate: Date
  indication: string
  totalUnits: number
  effectNotes?: string | null
  product?: { name: string } | null
  injections?: SummaryInjection[]
}

interface SummaryMuscle {
  id: string
  name: string
}

interface CopySummaryButtonProps {
  treatment: SummaryTreatment
  muscles: SummaryMuscle[]
  patientCode: string
}

export function CopySummaryButton({ treatment, muscles, patientCode }: CopySummaryButtonProps) {
  const [copied, setSetCopied] = useState(false)

  const handleCopy = () => {
    const dateStr = new Date(treatment.encounterLocalDate).toLocaleDateString()
    const product = treatment.product?.name || "N/A"
    const indication = treatment.indication
    
    // Format injections
    const injections = (treatment.injections || []).map((inj) => {
        const muscle = muscles.find(m => m.id === inj.muscleId)?.name || inj.muscleId || "Unknown"
        const side = inj.side === 'L' ? '(L)' : inj.side === 'R' ? '(R)' : inj.side === 'B' ? '(B)' : ''
        return `${muscle} ${side}: ${inj.units}U`
    }).join(", ")

    const summary = `Botulinum Toxin Treatment (${dateStr})
Patient: ${patientCode}
Indication: ${indication}
Product: ${product}
Total Dose: ${treatment.totalUnits}U
Sites: ${injections}
Notes: ${treatment.effectNotes || "None"}
---
Generated by InjexPro`

    navigator.clipboard.writeText(summary)
    setSetCopied(true)
    toast.success("Summary copied to clipboard")
    setTimeout(() => setSetCopied(false), 2000)
  }

  return (
    <Button 
        variant="outline" 
        size="sm" 
        onClick={handleCopy}
        className="h-8 gap-2"
    >
      {copied ? <Check className="size-3.5 text-green-500" /> : <ClipboardCopy className="size-3.5" />}
      {copied ? "Copied" : "Copy to EHR"}
    </Button>
  )
}